version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000 #${UID}
      context: ./
      dockerfile: Dockerfile
    image: shop-image
    container_name: shop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9003 remote_enable=1
      PHP_IDE_CONFIG: serverName=Docker


  db:
    image: mysql:5.7
    container_name: shop-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: site
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./Docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/